title: CS 127 Recitation
description: This websites purpose is to display the information we collected as a group, & to summarize our overall findings from our neighborhoods such as building age, Carbon Dioxide emissions, demographics, clean heating fuels, boilers, and more. The neighborhoods we anlyzed are Melrose, Pelham, 

theme: jekyll-theme-modernist
